### ISSUE TITLE
Favicon not showing

### ISSUE THREAD

**Issue by kamziksvk** [PaperMC/Travertine#131] opened 2020-06-30 11:58 UTC
Hello, after the latest release of travertine on version 1.16.1 my server icon stopped to appear in the serverlists. I have server icon created via the spigot rules: https://www.spigotmc.org/wiki/server-icon/

There is no error log in the console. Can you please provide me any help?

Thank you in advance!

**Comment by JRoy** [comment] 2020-06-30 12:53
Can you share the **exact** `server-icon.png` you're using?

**Comment by kamziksvk** [comment] 2020-06-30 12:56
Here you go - we have been using it several years without any problem - https://imgur.com/lGHIPEy

**Comment by JRoy** [comment] 2020-06-30 13:04
Cannot reproduce on latest Travertine. Check to make sure none of your bungee plugins are modifying the icon. Also, check to make sure ping passthrough is disabled.

**Comment by electronicboy** [comment] 2020-11-23 04:50
There appears to be a known issue with how the client shows the favicon that's been reported anecdotally over the past few months, nothing has changed here whatsoever, and this even occurs on vanilla, hence, closing

**Closed by electronicboy** 2020-11-23 04:50 UTC
