### ISSUE TITLE
Addition Request  : Provide an option to disable entity metadata rewriting (fixes PaperMC…  …#136)

### ISSUE THREAD

**Issue by alicheek** [PaperMC/Travertine#88] opened 2019-01-15 23:42 UTC
If possible could we get this merged to the travertine build as this will help alot with the meta packet disconnects for custom entity packets. 

: https://github.com/electronicboy/Waterfall/commit/1edde8dbafbcc3a15348c6e0564f0466a5495141

Thank you

**Comment by electronicboy** [comment] 2019-01-16 18:15
This will be merged into travertine once it's actually merged into waterfall

**Comment by Adam3055** [comment] 2019-01-19 20:35
Looks like this was just merged with Waterfall

So I would assume it won't be long until its merged with Travertine, I could be wrong though 

@electronicboy knows more then me :P

**Comment by alicheek** [comment] 2019-01-21 21:02
Looking forward to this! @electronicboy  thank you again for doing this though :)

**Comment by electronicboy** [comment] 2019-01-22 19:04
I've not had the time to setup a 1.7.x environment for testing, if people wanna help speed this up, please try the builds here and comment on your results;
https://keybase.pub/electronicboy/builds/travertine/Travertine-DisableEntityRemap.jar

**Comment by alicheek** [comment] 2019-01-22 19:08
Will give this a go as soon as I am back thank you

**Comment by Keaton1188** [comment] 2019-01-22 22:58
So far it seems good, updated 4 of our servers that used to have the problem and so far all is smooth :D

**Comment by TMCGH** [comment] 2019-01-24 18:18
Any updates on when this will be merged into travertine on the downloads page, or shall we just use the jar provided as our bungeecords jar (travertine) for the time being ?

**Comment by Keaton1188** [comment] 2019-01-24 20:35
One thing I have noticed @electronicboy is that if people log out in another DIM other than the overworld then try to get back in they won't be able to and will just get the message "Loading Terrain", moving them to spawn fixes this. 

Seems to have only started happening on this new version though, from one problem to another eh.. :P

**Comment by Time6628** [comment] 2019-02-06 18:10
Works.

**Comment by alicheek** [comment] 2019-02-06 18:44
Yea i would agree seems to be working great @electronicboy been a big help

**Comment by electronicboy** [comment] 2019-02-06 18:47
@Keaton1188 any updates? as for that matter, anybody able to reproduce that issue?

**Comment by Keaton1188** [comment] 2019-02-08 22:02
@electronicboy Not really, did some testing myself (logging out in the nether etc) and wasn't able to reproduce it but recently had a player that was stuck on "loading terrain" and said they logged out in the nether.. moved to spawn (overworld) and that sorted it.

Seems it doesn't always happen so its hard to reproduce :/

**Comment by Sharkske** [comment] 2019-02-25 10:41
Ok, so i tested this on my network and there is 2 issues caused but disabling entity metadata atless just for 1.7.10 servers, one error players got was this and it was client side causing the client to get sent back to fallback server and crashing them with error below player didn't send me the full report thats all i have

Error: java.lang.IllegalArgumentException: Could not get provider type for dimension 2, does not exist


2nd error i gotten is the biggest one i tested it on Project Ozone 2, FTB Infinity, or even 1.7.10 CrackPack, any 1.7.10 modpacks i check the proxy logs are bellow its only when going from the game/moded server back to the fallback server that it will cause the players client to crash the client crash report is bellow the proxy snapshot 

https://i.imgur.com/5uV14iY.png

java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.network.NetHandlerPlayClient.func_147247_a(NetHandlerPlayClient.java:1552)
	at net.minecraft.network.play.server.S3EPacketTeams.func_148833_a(SourceFile:100)
	at net.minecraft.network.play.server.S3EPacketTeams.func_148833_a(SourceFile:12)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Closed** 2019-04-22 21:24 UTC

**Comment by HeberonYT** [comment] 2019-07-22 20:24
@Sharkske did you solve the problem?
