### ISSUE TITLE
Players invisible 

### ISSUE THREAD

**Issue by maiks1986** [PaperMC/Travertine#141] opened 2020-08-31 00:01 UTC
I've been trying to fix this issue for hours now but it seems from all my tests that this problem is because of Travertine.
I'm using the latest build #158 and the problem isn't when I login directly to the Minecraft server. I also used latest buuild of spigot. Normally I'm using Waterfall also the latest build. 

What it all comes down to is that when I or other ppl logon we can't see each other. We can see chests opening, fireworks going off and arrows flying. Just not the player doing these things. It effects all players. 

I don't see any abnormalities in the log file. But here it is:
[01:25:49] [main/INFO]: Using mbed TLS based native cipher.
[01:25:49] [main/INFO]: Using zlib based native compressor.
[01:25:49] [main/INFO]: Enabled Travertine version git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:a24c106:158
[01:25:50] [main/INFO]: Not on Windows, attempting to use enhanced EpollEventLoop
[01:25:50] [main/INFO]: Epoll is working, utilising it!
[01:25:50] [main/INFO]: Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
[01:25:50] [main/INFO]: Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
[01:25:50] [main/INFO]: Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
[01:25:50] [main/INFO]: Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
[01:25:50] [main/INFO]: Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
[01:25:50] [main/INFO]: Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
[01:25:50] [main/INFO]: Loaded plugin reconnect_yaml version git:reconnect_yaml:1.16-R0.4-SNAPSHOT:a24c106:158 by WaterfallMC
[01:25:50] [main/INFO]: Loaded plugin cmd_find version git:cmd_find:1.16-R0.4-SNAPSHOT:a24c106:158 by WaterfallMC
[01:25:50] [main/INFO]: Loaded plugin cmd_server version git:cmd_server:1.16-R0.4-SNAPSHOT:a24c106:158 by WaterfallMC
[01:25:50] [main/INFO]: Loaded plugin cmd_alert version git:cmd_alert:1.16-R0.4-SNAPSHOT:a24c106:158 by WaterfallMC
[01:25:50] [main/INFO]: Loaded plugin cmd_send version git:cmd_send:1.16-R0.4-SNAPSHOT:a24c106:158 by WaterfallMC
[01:25:50] [main/INFO]: Loaded plugin cmd_list version git:cmd_list:1.16-R0.4-SNAPSHOT:a24c106:158 by WaterfallMC
[01:25:50] [main/WARN]: Forced host server pvp is not defined
[01:25:50] [main/INFO]: Enabled plugin reconnect_yaml version git:reconnect_yaml:1.16-R0.4-SNAPSHOT:a24c106:158 by WaterfallMC
[01:25:50] [main/INFO]: Enabled plugin cmd_find version git:cmd_find:1.16-R0.4-SNAPSHOT:a24c106:158 by WaterfallMC
[01:25:50] [main/INFO]: Enabled plugin cmd_server version git:cmd_server:1.16-R0.4-SNAPSHOT:a24c106:158 by WaterfallMC
[01:25:50] [main/INFO]: Enabled plugin cmd_alert version git:cmd_alert:1.16-R0.4-SNAPSHOT:a24c106:158 by WaterfallMC
[01:25:50] [main/INFO]: Enabled plugin cmd_send version git:cmd_send:1.16-R0.4-SNAPSHOT:a24c106:158 by WaterfallMC
[01:25:50] [main/INFO]: Enabled plugin cmd_list version git:cmd_list:1.16-R0.4-SNAPSHOT:a24c106:158 by WaterfallMC
[01:25:50] [Netty Boss IO Thread #0/INFO]: Listening on /0.0.0.0:25565
[01:26:16] [Netty Worker IO Thread #0/INFO]: [/82.161.93.115:57989] <-> InitialHandler has connected
[01:26:17] [Netty Worker IO Thread #0/INFO]: [Maiks86] disconnected with: Could not connect to a default or fallback server, please try again later: io.netty.channel.AbstractChannel$AnnotatedConnectException
[01:26:17] [Netty Worker IO Thread #0/INFO]: [/82.161.93.115:57989|Maiks86] -> UpstreamBridge has disconnected
[01:28:03] [Netty Worker IO Thread #1/INFO]: [/82.161.93.115:58004] <-> InitialHandler has connected
[01:28:04] [Netty Worker IO Thread #1/INFO]: [Maiks86|/82.161.93.115:58004] <-> ServerConnector [hub-1] has connected
[01:29:21] [Netty Worker IO Thread #2/INFO]: [/70.190.240.197:63711] <-> InitialHandler has pinged
[01:29:22] [Netty Worker IO Thread #3/INFO]: [/70.190.240.197:63712] <-> InitialHandler has connected
[01:29:23] [Netty Worker IO Thread #3/INFO]: [sheloves_drey|/70.190.240.197:63712] <-> ServerConnector [hub-1] has connected
[01:33:04] [Netty Worker IO Thread #3/INFO]: [/70.190.240.197:63712|sheloves_drey] -> UpstreamBridge has disconnected
[01:33:04] [Netty Worker IO Thread #3/INFO]: [/70.190.240.197:63712|sheloves_drey] <-> DownstreamBridge <-> [hub-1] has disconnected
[01:33:04] [Netty Worker IO Thread #4/INFO]: [/70.190.240.197:63780] <-> InitialHandler has pinged
[01:41:06] [Netty Worker IO Thread #1/INFO]: [Maiks86] disconnected with: Server closed
[01:41:06] [Netty Worker IO Thread #1/INFO]: [/82.161.93.115:58004|Maiks86] -> UpstreamBridge has disconnected
[01:41:06] [Netty Worker IO Thread #1/INFO]: [/82.161.93.115:58004|Maiks86] <-> DownstreamBridge <-> [hub-1] has disconnected
[01:47:18] [Netty Worker IO Thread #5/INFO]: [/82.161.93.115:58102] <-> InitialHandler has connected
[01:47:18] [Netty Worker IO Thread #5/INFO]: [Maiks86|/82.161.93.115:58102] <-> ServerConnector [hub-1] has connected
[01:48:42] [Netty Worker IO Thread #6/INFO]: [/70.190.240.197:63803] <-> InitialHandler has connected
[01:48:43] [Netty Worker IO Thread #6/INFO]: [sheloves_drey|/70.190.240.197:63803] <-> ServerConnector [hub-1] has connected
[01:49:59] [Netty Worker IO Thread #6/INFO]: [/70.190.240.197:63803|sheloves_drey] -> UpstreamBridge has disconnected
[01:49:59] [Netty Worker IO Thread #6/INFO]: [/70.190.240.197:63803|sheloves_drey] <-> DownstreamBridge <-> [hub-1] has disconnected
[01:49:59] [Netty Worker IO Thread #7/INFO]: [/70.190.240.197:63809] <-> InitialHandler has pinged

**Comment by Chew** [comment] 2020-08-31 00:26
Appears to be a duplicate of PaperMC/Waterfall#564

**Comment by electronicboy** [comment] 2020-08-31 09:28
99% of the time, this is due to plugins on the server sending data around with upsets bungee, with the information provided, we have 0 to go off
nonetheless, Duplicate of #564

**Closed by electronicboy** 2020-08-31 09:28 UTC

**Comment by maiks1986** [comment] 2020-08-31 19:30
All plugins are deleted!!!
